baseURL = 'http://Kyobito.github.io'
languageCode = 'en-us'
title = "Kyobito's Portfolio"
theme = "hugo-initio"

[params]
    name = "Kyobito"
    description = "Programmer, Coffee Drinker, Anime Enthusiast"
    email = "mystery@gmail.com"
    phone = "+1 000 000 0000"
    address = "123 Unknown Street, Seattle, WA"
    year = 2022
    avatar = "images/avatar.png"
    avatarclass = "circle"
    avatarborder = "expanded"
    background = ""
    banner = "images/bw-background2.jpg"
    favicon = "images/avatar.png"
    # Likely for each post; Not in the scope of this website
    DateForm = "June 24, 2022"
    author = "Kyobito"

    showSubheader = true
    showAboutSec = true
    showProjects = true
    showEducation = true
    showExperience = true
    showSkills = true

    showFooterContact = true
    showfooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = true

    [[menu.main]]
        name = "about"
        url = "/#about-section"
        weight = 1

    [[menu.main]]
        name = "projects"
        url = "/#projects"
        weight = 2

    [[menu.main]]
        name = "experience"
        url = "/#experience"
        weight = 4

    [[menu.main]]
        name = "education"
        url = "/#education"
        weight = 3

    [[menu.main]]
        name = "skills"
        url = "/#skills"
        weight = 5

    [[params.social]]
        title = "facebook"
        url = "https://www.facebook.com/nickname"
        icon = "fa-facebook-square"
        footer = true
        sharethis = true
        network = "facebook"
    
    [[params.social]]
        title = "twitter"
        url = "https://twitter.com/nickname"
        icon = "fab fa-twitter-square"
        footer = true
        sharethis = true
        network = "twitter"

    [[params.social]]
        title = "instagram"
        url = "https://www.instagram.com/nickname"
        icon = "fab fa-instagram"
        footer = true
        sharethis = false
        network = ""

    [[params.social]]
        title = "linkedin"
        url = "https://www.linkedin.com/in/nickname"
        icon = "fab fa-linkedin"
        footer = false
        sharethis = true
        network = "linkedin"

    [[params.social]]
        title = "github"
        url = "https://github.com/nickname"
        icon = "fab fa-github"
        footer = true
        sharethis = false
        network = ""

    [[params.social]]
        title = "email"
        url = "mailto:some.email@somewhere.com"
        icon = "fas fa-envelope-square"
        footer = false
        sharethis = true
        network = "email"

    [params.disqus]

    [params.google.analytics]